<div class="main-info" >
            <form action="" class="form-info">
                <h3>Thông tin hãng sữa</h3>
               <table class="info-sua">
                    <tr>
                        <th>Mã HS</th>
                        <th>Tên Hãng Sữa</th>
                        <th>Địa Chỉ</th>
                        <th>Điện Thoại</th>
                        <th>Email</th>
                    </tr>
                    <tr>
                        <td>VNM</td>
                        <td><a href="">Vinamilk</a></td>
                        <td>Trường đại học kiến trúc đà nẵng</td>
                        <td>0915582684</td>
                        <td>Vinamilk@gmail.com</td>
                    </tr>
                    <tr>
                        <td>NTF</td>
                        <td><a href="">NUTIFOOD</a></td>
                        <td>217/17 núi thành</td>
                        <td>0915582684</td>
                        <td>nuti@gmail.com</td>
                    </tr>
                    <tr>
                        <td>CGHL</td>
                        <td><a href="">Cô Gái Hà Lan</a></td>
                        <td>toà lanmart 81 vietnam</td>
                        <td>0915582684</td>
                        <td>CGHL@gmail.com</td>
                    </tr>
                    <tr>
                        <td>AB</td>
                        <td><a href="">Abbott</a></td>
                        <td>công ty sữa việt nam</td>
                        <td>0915582684</td>
                        <td>ABBOTT@gmail.com</td>
                    </tr>
                    <tr>
                        <td>DS</td>
                        <td><a href="">DASAN</a></td>
                        <td>Công ty nhập nhẩu nhật bản</td>
                        <td>0915582684</td>
                        <td>DASAN@gmail.com</td>
                    </tr>
                </table> 
            </form>
            
        </div>